first commit
Error. fix this
# Let's configure Reverse Proxy for this container so the world can see it!
nginx: the configuration file /etc/nginx/nginx.conf syntax is ok
nginx: configuration file /etc/nginx/nginx.conf test is successful
# 
# Download and transfer HAProxy config file
INFO[09-25|14:48:52] Pushing /var/lib/snapd/hostfs/home/johnmarkcausing/lemp/kkk.causingdesigns.net to /etc/nginx/sites-available/kkk.causingdesigns.net (file) 
Error: file does not exist
ln: target '/etc/nginx/sites-enabled/' is not a directory: No such file or directory
--verbose: 1: --verbose: nginx: not found
Failed to reload nginx.service: Unit nginx.service not found.
#
#
#